// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AccessPackage : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The access packages that are incompatible with this package. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackage>? AccessPackagesIncompatibleWith { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackage> AccessPackagesIncompatibleWith { get; set; }
#endif
        /// <summary>Read-only. Nullable. Supports $expand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>? AssignmentPolicies { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy> AssignmentPolicies { get; set; }
#endif
        /// <summary>Required when creating the access package. Read-only. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.AccessPackageCatalog? Catalog { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.AccessPackageCatalog Catalog { get; set; }
#endif
        /// <summary>The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>The description of the access package.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Required. The display name of the access package. Supports $filter (eq, contains).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The access packages whose assigned users are ineligible to be assigned this access package.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackage>? IncompatibleAccessPackages { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackage> IncompatibleAccessPackages { get; set; }
#endif
        /// <summary>The groups whose members are ineligible to be assigned this access package.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.Group>? IncompatibleGroups { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.Group> IncompatibleGroups { get; set; }
#endif
        /// <summary>Indicates whether the access package is hidden from the requestor.</summary>
        public bool? IsHidden { get; set; }
        /// <summary>The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z. Read-only.</summary>
        public DateTimeOffset? ModifiedDateTime { get; set; }
        /// <summary>The resource roles and scopes in this access package.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>? ResourceRoleScopes { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope> ResourceRoleScopes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.AccessPackage"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.AccessPackage CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.AccessPackage();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "accessPackagesIncompatibleWith", n => { AccessPackagesIncompatibleWith = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>(global::MissAlise.OneDrive.Models.AccessPackage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assignmentPolicies", n => { AssignmentPolicies = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>(global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "catalog", n => { Catalog = n.GetObjectValue<global::MissAlise.OneDrive.Models.AccessPackageCatalog>(global::MissAlise.OneDrive.Models.AccessPackageCatalog.CreateFromDiscriminatorValue); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "incompatibleAccessPackages", n => { IncompatibleAccessPackages = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>(global::MissAlise.OneDrive.Models.AccessPackage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "incompatibleGroups", n => { IncompatibleGroups = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Group>(global::MissAlise.OneDrive.Models.Group.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isHidden", n => { IsHidden = n.GetBoolValue(); } },
                { "modifiedDateTime", n => { ModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "resourceRoleScopes", n => { ResourceRoleScopes = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>(global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>("accessPackagesIncompatibleWith", AccessPackagesIncompatibleWith);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>("assignmentPolicies", AssignmentPolicies);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.AccessPackageCatalog>("catalog", Catalog);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>("incompatibleAccessPackages", IncompatibleAccessPackages);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Group>("incompatibleGroups", IncompatibleGroups);
            writer.WriteBoolValue("isHidden", IsHidden);
            writer.WriteDateTimeOffsetValue("modifiedDateTime", ModifiedDateTime);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>("resourceRoleScopes", ResourceRoleScopes);
        }
    }
}
#pragma warning restore CS0618
