// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuditLogRoot : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The directoryAudits property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.DirectoryAudit>? DirectoryAudits { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.DirectoryAudit> DirectoryAudits { get; set; }
#endif
        /// <summary>The provisioning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.ProvisioningObjectSummary>? Provisioning { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.ProvisioningObjectSummary> Provisioning { get; set; }
#endif
        /// <summary>The signIns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SignIn>? SignIns { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SignIn> SignIns { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.AuditLogRoot"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.AuditLogRoot CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.AuditLogRoot();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "directoryAudits", n => { DirectoryAudits = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DirectoryAudit>(global::MissAlise.OneDrive.Models.DirectoryAudit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "provisioning", n => { Provisioning = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ProvisioningObjectSummary>(global::MissAlise.OneDrive.Models.ProvisioningObjectSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "signIns", n => { SignIns = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SignIn>(global::MissAlise.OneDrive.Models.SignIn.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DirectoryAudit>("directoryAudits", DirectoryAudits);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ProvisioningObjectSummary>("provisioning", Provisioning);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SignIn>("signIns", SignIns);
        }
    }
}
#pragma warning restore CS0618
