// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthenticationMethodFeatureConfiguration : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>A single entity that is excluded from this feature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.FeatureTarget? ExcludeTarget { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.FeatureTarget ExcludeTarget { get; set; }
#endif
        /// <summary>A single entity that is included in this feature.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.FeatureTarget? IncludeTarget { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.FeatureTarget IncludeTarget { get; set; }
#endif
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Enable or disable the feature. Possible values are: default, enabled, disabled, unknownFutureValue. The default value is used when the configuration hasn&apos;t been explicitly set and uses the default behavior of Microsoft Entra ID for the setting. The default value is disabled.</summary>
        public global::MissAlise.OneDrive.Models.AdvancedConfigState? State { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.AuthenticationMethodFeatureConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.AuthenticationMethodFeatureConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.AuthenticationMethodFeatureConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "excludeTarget", n => { ExcludeTarget = n.GetObjectValue<global::MissAlise.OneDrive.Models.FeatureTarget>(global::MissAlise.OneDrive.Models.FeatureTarget.CreateFromDiscriminatorValue); } },
                { "includeTarget", n => { IncludeTarget = n.GetObjectValue<global::MissAlise.OneDrive.Models.FeatureTarget>(global::MissAlise.OneDrive.Models.FeatureTarget.CreateFromDiscriminatorValue); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::MissAlise.OneDrive.Models.AdvancedConfigState>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.FeatureTarget>("excludeTarget", ExcludeTarget);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.FeatureTarget>("includeTarget", IncludeTarget);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.AdvancedConfigState>("state", State);
        }
    }
}
#pragma warning restore CS0618
