// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutomaticRepliesSetting : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The set of audience external to the signed-in user&apos;s organization who will receive the ExternalReplyMessage, if Status is AlwaysEnabled or Scheduled. The possible values are: none, contactsOnly, all.</summary>
        public global::MissAlise.OneDrive.Models.ExternalAudienceScope? ExternalAudience { get; set; }
        /// <summary>The automatic reply to send to the specified external audience, if Status is AlwaysEnabled or Scheduled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalReplyMessage { get; set; }
#nullable restore
#else
        public string ExternalReplyMessage { get; set; }
#endif
        /// <summary>The automatic reply to send to the audience internal to the signed-in user&apos;s organization, if Status is AlwaysEnabled or Scheduled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalReplyMessage { get; set; }
#nullable restore
#else
        public string InternalReplyMessage { get; set; }
#endif
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>The date and time that automatic replies are set to end, if Status is set to Scheduled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DateTimeTimeZone? ScheduledEndDateTime { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DateTimeTimeZone ScheduledEndDateTime { get; set; }
#endif
        /// <summary>The date and time that automatic replies are set to begin, if Status is set to Scheduled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DateTimeTimeZone? ScheduledStartDateTime { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DateTimeTimeZone ScheduledStartDateTime { get; set; }
#endif
        /// <summary>Configurations status for automatic replies. The possible values are: disabled, alwaysEnabled, scheduled.</summary>
        public global::MissAlise.OneDrive.Models.AutomaticRepliesStatus? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.AutomaticRepliesSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.AutomaticRepliesSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.AutomaticRepliesSetting();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "externalAudience", n => { ExternalAudience = n.GetEnumValue<global::MissAlise.OneDrive.Models.ExternalAudienceScope>(); } },
                { "externalReplyMessage", n => { ExternalReplyMessage = n.GetStringValue(); } },
                { "internalReplyMessage", n => { InternalReplyMessage = n.GetStringValue(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "scheduledEndDateTime", n => { ScheduledEndDateTime = n.GetObjectValue<global::MissAlise.OneDrive.Models.DateTimeTimeZone>(global::MissAlise.OneDrive.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "scheduledStartDateTime", n => { ScheduledStartDateTime = n.GetObjectValue<global::MissAlise.OneDrive.Models.DateTimeTimeZone>(global::MissAlise.OneDrive.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::MissAlise.OneDrive.Models.AutomaticRepliesStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.ExternalAudienceScope>("externalAudience", ExternalAudience);
            writer.WriteStringValue("externalReplyMessage", ExternalReplyMessage);
            writer.WriteStringValue("internalReplyMessage", InternalReplyMessage);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DateTimeTimeZone>("scheduledEndDateTime", ScheduledEndDateTime);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DateTimeTimeZone>("scheduledStartDateTime", ScheduledStartDateTime);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.AutomaticRepliesStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
