// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommsOperation : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Unique Client Context string. Max limit is 256 chars.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientContext { get; set; }
#nullable restore
#else
        public string ClientContext { get; set; }
#endif
        /// <summary>The result information. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ResultInfo? ResultInfo { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ResultInfo ResultInfo { get; set; }
#endif
        /// <summary>The status property</summary>
        public global::MissAlise.OneDrive.Models.OperationStatus? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.CommsOperation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.CommsOperation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.addLargeGalleryViewOperation" => new global::MissAlise.OneDrive.Models.AddLargeGalleryViewOperation(),
                "#microsoft.graph.cancelMediaProcessingOperation" => new global::MissAlise.OneDrive.Models.CancelMediaProcessingOperation(),
                "#microsoft.graph.inviteParticipantsOperation" => new global::MissAlise.OneDrive.Models.InviteParticipantsOperation(),
                "#microsoft.graph.muteParticipantOperation" => new global::MissAlise.OneDrive.Models.MuteParticipantOperation(),
                "#microsoft.graph.playPromptOperation" => new global::MissAlise.OneDrive.Models.PlayPromptOperation(),
                "#microsoft.graph.recordOperation" => new global::MissAlise.OneDrive.Models.RecordOperation(),
                "#microsoft.graph.sendDtmfTonesOperation" => new global::MissAlise.OneDrive.Models.SendDtmfTonesOperation(),
                "#microsoft.graph.startHoldMusicOperation" => new global::MissAlise.OneDrive.Models.StartHoldMusicOperation(),
                "#microsoft.graph.stopHoldMusicOperation" => new global::MissAlise.OneDrive.Models.StopHoldMusicOperation(),
                "#microsoft.graph.subscribeToToneOperation" => new global::MissAlise.OneDrive.Models.SubscribeToToneOperation(),
                "#microsoft.graph.unmuteParticipantOperation" => new global::MissAlise.OneDrive.Models.UnmuteParticipantOperation(),
                "#microsoft.graph.updateRecordingStatusOperation" => new global::MissAlise.OneDrive.Models.UpdateRecordingStatusOperation(),
                _ => new global::MissAlise.OneDrive.Models.CommsOperation(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "clientContext", n => { ClientContext = n.GetStringValue(); } },
                { "resultInfo", n => { ResultInfo = n.GetObjectValue<global::MissAlise.OneDrive.Models.ResultInfo>(global::MissAlise.OneDrive.Models.ResultInfo.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::MissAlise.OneDrive.Models.OperationStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteStringValue("clientContext", ClientContext);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ResultInfo>("resultInfo", ResultInfo);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.OperationStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
