// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConditionalAccessRoot : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Read-only. Nullable. Returns a collection of the specified authentication context class references.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AuthenticationContextClassReference>? AuthenticationContextClassReferences { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AuthenticationContextClassReference> AuthenticationContextClassReferences { get; set; }
#endif
        /// <summary>The authenticationStrength property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.AuthenticationStrengthRoot? AuthenticationStrength { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.AuthenticationStrengthRoot AuthenticationStrength { get; set; }
#endif
        /// <summary>Read-only. Nullable. Returns a collection of the specified named locations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.NamedLocation>? NamedLocations { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.NamedLocation> NamedLocations { get; set; }
#endif
        /// <summary>Read-only. Nullable. Returns a collection of the specified Conditional Access (CA) policies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.ConditionalAccessPolicy>? Policies { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.ConditionalAccessPolicy> Policies { get; set; }
#endif
        /// <summary>Read-only. Nullable. Returns a collection of the specified Conditional Access templates.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.ConditionalAccessTemplate>? Templates { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.ConditionalAccessTemplate> Templates { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.ConditionalAccessRoot"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.ConditionalAccessRoot CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.ConditionalAccessRoot();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "authenticationContextClassReferences", n => { AuthenticationContextClassReferences = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AuthenticationContextClassReference>(global::MissAlise.OneDrive.Models.AuthenticationContextClassReference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "authenticationStrength", n => { AuthenticationStrength = n.GetObjectValue<global::MissAlise.OneDrive.Models.AuthenticationStrengthRoot>(global::MissAlise.OneDrive.Models.AuthenticationStrengthRoot.CreateFromDiscriminatorValue); } },
                { "namedLocations", n => { NamedLocations = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.NamedLocation>(global::MissAlise.OneDrive.Models.NamedLocation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "policies", n => { Policies = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConditionalAccessPolicy>(global::MissAlise.OneDrive.Models.ConditionalAccessPolicy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "templates", n => { Templates = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConditionalAccessTemplate>(global::MissAlise.OneDrive.Models.ConditionalAccessTemplate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AuthenticationContextClassReference>("authenticationContextClassReferences", AuthenticationContextClassReferences);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.AuthenticationStrengthRoot>("authenticationStrength", AuthenticationStrength);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.NamedLocation>("namedLocations", NamedLocations);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConditionalAccessPolicy>("policies", Policies);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConditionalAccessTemplate>("templates", Templates);
        }
    }
}
#pragma warning restore CS0618
