// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    /// <summary>
    /// Device Configuration.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeviceConfiguration : global::MissAlise.OneDrive.Models.Entity, IParsable
    {
        /// <summary>The list of assignments for the device configuration profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationAssignment>? Assignments { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationAssignment> Assignments { get; set; }
#endif
        /// <summary>DateTime the object was created.</summary>
        public DateTimeOffset? CreatedDateTime { get; set; }
        /// <summary>Admin provided description of the Device Configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Device Configuration Setting State Device Summary</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SettingStateDeviceSummary>? DeviceSettingStateSummaries { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SettingStateDeviceSummary> DeviceSettingStateSummaries { get; set; }
#endif
        /// <summary>Device configuration installation status by device.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceStatus>? DeviceStatuses { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceStatus> DeviceStatuses { get; set; }
#endif
        /// <summary>Device Configuration devices status overview</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceOverview? DeviceStatusOverview { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceOverview DeviceStatusOverview { get; set; }
#endif
        /// <summary>Admin provided name of the device configuration.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>DateTime the object was last modified.</summary>
        public DateTimeOffset? LastModifiedDateTime { get; set; }
        /// <summary>Device configuration installation status by user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationUserStatus>? UserStatuses { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.DeviceConfigurationUserStatus> UserStatuses { get; set; }
#endif
        /// <summary>Device Configuration users status overview</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DeviceConfigurationUserOverview? UserStatusOverview { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DeviceConfigurationUserOverview UserStatusOverview { get; set; }
#endif
        /// <summary>Version of the device configuration.</summary>
        public int? Version { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.DeviceConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.DeviceConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.androidCustomConfiguration" => new global::MissAlise.OneDrive.Models.AndroidCustomConfiguration(),
                "#microsoft.graph.androidGeneralDeviceConfiguration" => new global::MissAlise.OneDrive.Models.AndroidGeneralDeviceConfiguration(),
                "#microsoft.graph.androidWorkProfileCustomConfiguration" => new global::MissAlise.OneDrive.Models.AndroidWorkProfileCustomConfiguration(),
                "#microsoft.graph.androidWorkProfileGeneralDeviceConfiguration" => new global::MissAlise.OneDrive.Models.AndroidWorkProfileGeneralDeviceConfiguration(),
                "#microsoft.graph.appleDeviceFeaturesConfigurationBase" => new global::MissAlise.OneDrive.Models.AppleDeviceFeaturesConfigurationBase(),
                "#microsoft.graph.editionUpgradeConfiguration" => new global::MissAlise.OneDrive.Models.EditionUpgradeConfiguration(),
                "#microsoft.graph.iosCertificateProfile" => new global::MissAlise.OneDrive.Models.IosCertificateProfile(),
                "#microsoft.graph.iosCustomConfiguration" => new global::MissAlise.OneDrive.Models.IosCustomConfiguration(),
                "#microsoft.graph.iosDeviceFeaturesConfiguration" => new global::MissAlise.OneDrive.Models.IosDeviceFeaturesConfiguration(),
                "#microsoft.graph.iosGeneralDeviceConfiguration" => new global::MissAlise.OneDrive.Models.IosGeneralDeviceConfiguration(),
                "#microsoft.graph.iosUpdateConfiguration" => new global::MissAlise.OneDrive.Models.IosUpdateConfiguration(),
                "#microsoft.graph.macOSCustomConfiguration" => new global::MissAlise.OneDrive.Models.MacOSCustomConfiguration(),
                "#microsoft.graph.macOSDeviceFeaturesConfiguration" => new global::MissAlise.OneDrive.Models.MacOSDeviceFeaturesConfiguration(),
                "#microsoft.graph.macOSGeneralDeviceConfiguration" => new global::MissAlise.OneDrive.Models.MacOSGeneralDeviceConfiguration(),
                "#microsoft.graph.sharedPCConfiguration" => new global::MissAlise.OneDrive.Models.SharedPCConfiguration(),
                "#microsoft.graph.windows10CustomConfiguration" => new global::MissAlise.OneDrive.Models.Windows10CustomConfiguration(),
                "#microsoft.graph.windows10EndpointProtectionConfiguration" => new global::MissAlise.OneDrive.Models.Windows10EndpointProtectionConfiguration(),
                "#microsoft.graph.windows10EnterpriseModernAppManagementConfiguration" => new global::MissAlise.OneDrive.Models.Windows10EnterpriseModernAppManagementConfiguration(),
                "#microsoft.graph.windows10GeneralConfiguration" => new global::MissAlise.OneDrive.Models.Windows10GeneralConfiguration(),
                "#microsoft.graph.windows10SecureAssessmentConfiguration" => new global::MissAlise.OneDrive.Models.Windows10SecureAssessmentConfiguration(),
                "#microsoft.graph.windows10TeamGeneralConfiguration" => new global::MissAlise.OneDrive.Models.Windows10TeamGeneralConfiguration(),
                "#microsoft.graph.windows81GeneralConfiguration" => new global::MissAlise.OneDrive.Models.Windows81GeneralConfiguration(),
                "#microsoft.graph.windowsDefenderAdvancedThreatProtectionConfiguration" => new global::MissAlise.OneDrive.Models.WindowsDefenderAdvancedThreatProtectionConfiguration(),
                "#microsoft.graph.windowsPhone81CustomConfiguration" => new global::MissAlise.OneDrive.Models.WindowsPhone81CustomConfiguration(),
                "#microsoft.graph.windowsPhone81GeneralConfiguration" => new global::MissAlise.OneDrive.Models.WindowsPhone81GeneralConfiguration(),
                "#microsoft.graph.windowsUpdateForBusinessConfiguration" => new global::MissAlise.OneDrive.Models.WindowsUpdateForBusinessConfiguration(),
                _ => new global::MissAlise.OneDrive.Models.DeviceConfiguration(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "assignments", n => { Assignments = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationAssignment>(global::MissAlise.OneDrive.Models.DeviceConfigurationAssignment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "createdDateTime", n => { CreatedDateTime = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "deviceSettingStateSummaries", n => { DeviceSettingStateSummaries = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SettingStateDeviceSummary>(global::MissAlise.OneDrive.Models.SettingStateDeviceSummary.CreateFromDiscriminatorValue)?.AsList(); } },
                { "deviceStatusOverview", n => { DeviceStatusOverview = n.GetObjectValue<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceOverview>(global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceOverview.CreateFromDiscriminatorValue); } },
                { "deviceStatuses", n => { DeviceStatuses = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceStatus>(global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceStatus.CreateFromDiscriminatorValue)?.AsList(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "userStatusOverview", n => { UserStatusOverview = n.GetObjectValue<global::MissAlise.OneDrive.Models.DeviceConfigurationUserOverview>(global::MissAlise.OneDrive.Models.DeviceConfigurationUserOverview.CreateFromDiscriminatorValue); } },
                { "userStatuses", n => { UserStatuses = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationUserStatus>(global::MissAlise.OneDrive.Models.DeviceConfigurationUserStatus.CreateFromDiscriminatorValue)?.AsList(); } },
                { "version", n => { Version = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationAssignment>("assignments", Assignments);
            writer.WriteDateTimeOffsetValue("createdDateTime", CreatedDateTime);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SettingStateDeviceSummary>("deviceSettingStateSummaries", DeviceSettingStateSummaries);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceStatus>("deviceStatuses", DeviceStatuses);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DeviceConfigurationDeviceOverview>("deviceStatusOverview", DeviceStatusOverview);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteDateTimeOffsetValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.DeviceConfigurationUserStatus>("userStatuses", UserStatuses);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DeviceConfigurationUserOverview>("userStatusOverview", UserStatusOverview);
            writer.WriteIntValue("version", Version);
        }
    }
}
#pragma warning restore CS0618
