// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EducationClass : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>All categories associated with this class. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationCategory>? AssignmentCategories { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationCategory> AssignmentCategories { get; set; }
#endif
        /// <summary>Specifies class-level defaults respected by new assignments created in the class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.EducationAssignmentDefaults? AssignmentDefaults { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.EducationAssignmentDefaults AssignmentDefaults { get; set; }
#endif
        /// <summary>All assignments associated with this class. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationAssignment>? Assignments { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationAssignment> Assignments { get; set; }
#endif
        /// <summary>Specifies class-level assignments settings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.EducationAssignmentSettings? AssignmentSettings { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.EducationAssignmentSettings AssignmentSettings { get; set; }
#endif
        /// <summary>Class code used by the school to identify the class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClassCode { get; set; }
#nullable restore
#else
        public string ClassCode { get; set; }
#endif
        /// <summary>The course property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.EducationCourse? Course { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.EducationCourse Course { get; set; }
#endif
        /// <summary>Entity who created the class</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.IdentitySet? CreatedBy { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.IdentitySet CreatedBy { get; set; }
#endif
        /// <summary>Description of the class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Name of the class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>ID of the class from the syncing system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalId { get; set; }
#nullable restore
#else
        public string ExternalId { get; set; }
#endif
        /// <summary>Name of the class in the syncing system.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalName { get; set; }
#nullable restore
#else
        public string ExternalName { get; set; }
#endif
        /// <summary>How this class was created. Possible values are: sis, manual.</summary>
        public global::MissAlise.OneDrive.Models.EducationExternalSource? ExternalSource { get; set; }
        /// <summary>The name of the external source this resource was generated from.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalSourceDetail { get; set; }
#nullable restore
#else
        public string ExternalSourceDetail { get; set; }
#endif
        /// <summary>Grade level of the class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Grade { get; set; }
#nullable restore
#else
        public string Grade { get; set; }
#endif
        /// <summary>The underlying Microsoft 365 group object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Group? Group { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Group Group { get; set; }
#endif
        /// <summary>Mail name for sending email to all members, if this is enabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MailNickname { get; set; }
#nullable restore
#else
        public string MailNickname { get; set; }
#endif
        /// <summary>All users in the class. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationUser>? Members { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationUser> Members { get; set; }
#endif
        /// <summary>All modules in the class. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationModule>? Modules { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationModule> Modules { get; set; }
#endif
        /// <summary>All schools that this class is associated with. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationSchool>? Schools { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationSchool> Schools { get; set; }
#endif
        /// <summary>All teachers in the class. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.EducationUser>? Teachers { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.EducationUser> Teachers { get; set; }
#endif
        /// <summary>Term for this class.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.EducationTerm? Term { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.EducationTerm Term { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.EducationClass"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.EducationClass CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.EducationClass();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "assignmentCategories", n => { AssignmentCategories = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationCategory>(global::MissAlise.OneDrive.Models.EducationCategory.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assignmentDefaults", n => { AssignmentDefaults = n.GetObjectValue<global::MissAlise.OneDrive.Models.EducationAssignmentDefaults>(global::MissAlise.OneDrive.Models.EducationAssignmentDefaults.CreateFromDiscriminatorValue); } },
                { "assignmentSettings", n => { AssignmentSettings = n.GetObjectValue<global::MissAlise.OneDrive.Models.EducationAssignmentSettings>(global::MissAlise.OneDrive.Models.EducationAssignmentSettings.CreateFromDiscriminatorValue); } },
                { "assignments", n => { Assignments = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationAssignment>(global::MissAlise.OneDrive.Models.EducationAssignment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "classCode", n => { ClassCode = n.GetStringValue(); } },
                { "course", n => { Course = n.GetObjectValue<global::MissAlise.OneDrive.Models.EducationCourse>(global::MissAlise.OneDrive.Models.EducationCourse.CreateFromDiscriminatorValue); } },
                { "createdBy", n => { CreatedBy = n.GetObjectValue<global::MissAlise.OneDrive.Models.IdentitySet>(global::MissAlise.OneDrive.Models.IdentitySet.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "externalId", n => { ExternalId = n.GetStringValue(); } },
                { "externalName", n => { ExternalName = n.GetStringValue(); } },
                { "externalSource", n => { ExternalSource = n.GetEnumValue<global::MissAlise.OneDrive.Models.EducationExternalSource>(); } },
                { "externalSourceDetail", n => { ExternalSourceDetail = n.GetStringValue(); } },
                { "grade", n => { Grade = n.GetStringValue(); } },
                { "group", n => { Group = n.GetObjectValue<global::MissAlise.OneDrive.Models.Group>(global::MissAlise.OneDrive.Models.Group.CreateFromDiscriminatorValue); } },
                { "mailNickname", n => { MailNickname = n.GetStringValue(); } },
                { "members", n => { Members = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationUser>(global::MissAlise.OneDrive.Models.EducationUser.CreateFromDiscriminatorValue)?.AsList(); } },
                { "modules", n => { Modules = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationModule>(global::MissAlise.OneDrive.Models.EducationModule.CreateFromDiscriminatorValue)?.AsList(); } },
                { "schools", n => { Schools = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationSchool>(global::MissAlise.OneDrive.Models.EducationSchool.CreateFromDiscriminatorValue)?.AsList(); } },
                { "teachers", n => { Teachers = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationUser>(global::MissAlise.OneDrive.Models.EducationUser.CreateFromDiscriminatorValue)?.AsList(); } },
                { "term", n => { Term = n.GetObjectValue<global::MissAlise.OneDrive.Models.EducationTerm>(global::MissAlise.OneDrive.Models.EducationTerm.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationCategory>("assignmentCategories", AssignmentCategories);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.EducationAssignmentDefaults>("assignmentDefaults", AssignmentDefaults);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationAssignment>("assignments", Assignments);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.EducationAssignmentSettings>("assignmentSettings", AssignmentSettings);
            writer.WriteStringValue("classCode", ClassCode);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.EducationCourse>("course", Course);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.IdentitySet>("createdBy", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteStringValue("externalId", ExternalId);
            writer.WriteStringValue("externalName", ExternalName);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.EducationExternalSource>("externalSource", ExternalSource);
            writer.WriteStringValue("externalSourceDetail", ExternalSourceDetail);
            writer.WriteStringValue("grade", Grade);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Group>("group", Group);
            writer.WriteStringValue("mailNickname", MailNickname);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationUser>("members", Members);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationModule>("modules", Modules);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationSchool>("schools", Schools);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.EducationUser>("teachers", Teachers);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.EducationTerm>("term", Term);
        }
    }
}
#pragma warning restore CS0618
