// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EntitlementManagement : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Approval stages for decisions associated with access package assignment requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.Approval>? AccessPackageAssignmentApprovals { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.Approval> AccessPackageAssignmentApprovals { get; set; }
#endif
        /// <summary>Access packages define the collection of resource roles and the policies for which subjects can request or be assigned access to those resources.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackage>? AccessPackages { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackage> AccessPackages { get; set; }
#endif
        /// <summary>Access package assignment policies govern which subjects can request or be assigned an access package via an access package assignment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>? AssignmentPolicies { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy> AssignmentPolicies { get; set; }
#endif
        /// <summary>Access package assignment requests created by or on behalf of a subject.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentRequest>? AssignmentRequests { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignmentRequest> AssignmentRequests { get; set; }
#endif
        /// <summary>The assignment of an access package to a subject for a period of time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignment>? Assignments { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageAssignment> Assignments { get; set; }
#endif
        /// <summary>A container for access packages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageCatalog>? Catalogs { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageCatalog> Catalogs { get; set; }
#endif
        /// <summary>References to a directory or domain of another organization whose users can request access.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.ConnectedOrganization>? ConnectedOrganizations { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.ConnectedOrganization> ConnectedOrganizations { get; set; }
#endif
        /// <summary>A reference to the geolocation environments in which a resource is located.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceEnvironment>? ResourceEnvironments { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceEnvironment> ResourceEnvironments { get; set; }
#endif
        /// <summary>Represents a request to add or remove a resource to or from a catalog respectively.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRequest>? ResourceRequests { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRequest> ResourceRequests { get; set; }
#endif
        /// <summary>The resourceRoleScopes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>? ResourceRoleScopes { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope> ResourceRoleScopes { get; set; }
#endif
        /// <summary>The resources associated with the catalogs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.AccessPackageResource>? Resources { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.AccessPackageResource> Resources { get; set; }
#endif
        /// <summary>The settings that control the behavior of Microsoft Entra entitlement management.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.EntitlementManagementSettings? Settings { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.EntitlementManagementSettings Settings { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.EntitlementManagement"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.EntitlementManagement CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.EntitlementManagement();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "accessPackageAssignmentApprovals", n => { AccessPackageAssignmentApprovals = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Approval>(global::MissAlise.OneDrive.Models.Approval.CreateFromDiscriminatorValue)?.AsList(); } },
                { "accessPackages", n => { AccessPackages = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>(global::MissAlise.OneDrive.Models.AccessPackage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assignmentPolicies", n => { AssignmentPolicies = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>(global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assignmentRequests", n => { AssignmentRequests = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentRequest>(global::MissAlise.OneDrive.Models.AccessPackageAssignmentRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "assignments", n => { Assignments = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignment>(global::MissAlise.OneDrive.Models.AccessPackageAssignment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "catalogs", n => { Catalogs = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageCatalog>(global::MissAlise.OneDrive.Models.AccessPackageCatalog.CreateFromDiscriminatorValue)?.AsList(); } },
                { "connectedOrganizations", n => { ConnectedOrganizations = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConnectedOrganization>(global::MissAlise.OneDrive.Models.ConnectedOrganization.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resourceEnvironments", n => { ResourceEnvironments = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceEnvironment>(global::MissAlise.OneDrive.Models.AccessPackageResourceEnvironment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resourceRequests", n => { ResourceRequests = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRequest>(global::MissAlise.OneDrive.Models.AccessPackageResourceRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resourceRoleScopes", n => { ResourceRoleScopes = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>(global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope.CreateFromDiscriminatorValue)?.AsList(); } },
                { "resources", n => { Resources = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResource>(global::MissAlise.OneDrive.Models.AccessPackageResource.CreateFromDiscriminatorValue)?.AsList(); } },
                { "settings", n => { Settings = n.GetObjectValue<global::MissAlise.OneDrive.Models.EntitlementManagementSettings>(global::MissAlise.OneDrive.Models.EntitlementManagementSettings.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Approval>("accessPackageAssignmentApprovals", AccessPackageAssignmentApprovals);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackage>("accessPackages", AccessPackages);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentPolicy>("assignmentPolicies", AssignmentPolicies);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignmentRequest>("assignmentRequests", AssignmentRequests);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageAssignment>("assignments", Assignments);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageCatalog>("catalogs", Catalogs);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ConnectedOrganization>("connectedOrganizations", ConnectedOrganizations);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceEnvironment>("resourceEnvironments", ResourceEnvironments);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRequest>("resourceRequests", ResourceRequests);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResourceRoleScope>("resourceRoleScopes", ResourceRoleScopes);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.AccessPackageResource>("resources", Resources);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.EntitlementManagementSettings>("settings", Settings);
        }
    }
}
#pragma warning restore CS0618
