// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ItemActivityStat : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Statistics about the access actions in this interval. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ItemActionStat? Access { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ItemActionStat Access { get; set; }
#endif
        /// <summary>Exposes the itemActivities represented in this itemActivityStat resource.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.ItemActivity>? Activities { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.ItemActivity> Activities { get; set; }
#endif
        /// <summary>Statistics about the create actions in this interval. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ItemActionStat? Create { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ItemActionStat Create { get; set; }
#endif
        /// <summary>Statistics about the delete actions in this interval. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ItemActionStat? Delete { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ItemActionStat Delete { get; set; }
#endif
        /// <summary>Statistics about the edit actions in this interval. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ItemActionStat? Edit { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ItemActionStat Edit { get; set; }
#endif
        /// <summary>When the interval ends. Read-only.</summary>
        public DateTimeOffset? EndDateTime { get; set; }
        /// <summary>Indicates that the statistics in this interval are based on incomplete data. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.IncompleteData? IncompleteData { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.IncompleteData IncompleteData { get; set; }
#endif
        /// <summary>Indicates whether the item is &apos;trending.&apos; Read-only.</summary>
        public bool? IsTrending { get; set; }
        /// <summary>Statistics about the move actions in this interval. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.ItemActionStat? Move { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.ItemActionStat Move { get; set; }
#endif
        /// <summary>When the interval starts. Read-only.</summary>
        public DateTimeOffset? StartDateTime { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.ItemActivityStat"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.ItemActivityStat CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.ItemActivityStat();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "access", n => { Access = n.GetObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>(global::MissAlise.OneDrive.Models.ItemActionStat.CreateFromDiscriminatorValue); } },
                { "activities", n => { Activities = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ItemActivity>(global::MissAlise.OneDrive.Models.ItemActivity.CreateFromDiscriminatorValue)?.AsList(); } },
                { "create", n => { Create = n.GetObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>(global::MissAlise.OneDrive.Models.ItemActionStat.CreateFromDiscriminatorValue); } },
                { "delete", n => { Delete = n.GetObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>(global::MissAlise.OneDrive.Models.ItemActionStat.CreateFromDiscriminatorValue); } },
                { "edit", n => { Edit = n.GetObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>(global::MissAlise.OneDrive.Models.ItemActionStat.CreateFromDiscriminatorValue); } },
                { "endDateTime", n => { EndDateTime = n.GetDateTimeOffsetValue(); } },
                { "incompleteData", n => { IncompleteData = n.GetObjectValue<global::MissAlise.OneDrive.Models.IncompleteData>(global::MissAlise.OneDrive.Models.IncompleteData.CreateFromDiscriminatorValue); } },
                { "isTrending", n => { IsTrending = n.GetBoolValue(); } },
                { "move", n => { Move = n.GetObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>(global::MissAlise.OneDrive.Models.ItemActionStat.CreateFromDiscriminatorValue); } },
                { "startDateTime", n => { StartDateTime = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>("access", Access);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.ItemActivity>("activities", Activities);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>("create", Create);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>("delete", Delete);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>("edit", Edit);
            writer.WriteDateTimeOffsetValue("endDateTime", EndDateTime);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.IncompleteData>("incompleteData", IncompleteData);
            writer.WriteBoolValue("isTrending", IsTrending);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.ItemActionStat>("move", Move);
            writer.WriteDateTimeOffsetValue("startDateTime", StartDateTime);
        }
    }
}
#pragma warning restore CS0618
