// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MembershipOutlierInsight : global::MissAlise.OneDrive.Models.GovernanceInsight, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Navigation link to the container directory object. For example, to a group.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DirectoryObject? Container { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DirectoryObject Container { get; set; }
#endif
        /// <summary>Indicates the identifier of the container, for example, a group ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContainerId { get; set; }
#nullable restore
#else
        public string ContainerId { get; set; }
#endif
        /// <summary>Navigation link to a member object who modified the record. For example, to a user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.User? LastModifiedBy { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.User LastModifiedBy { get; set; }
#endif
        /// <summary>Navigation link to a member object. For example, to a user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.DirectoryObject? Member { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.DirectoryObject Member { get; set; }
#endif
        /// <summary>Indicates the identifier of the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MemberId { get; set; }
#nullable restore
#else
        public string MemberId { get; set; }
#endif
        /// <summary>The outlierContainerType property</summary>
        public global::MissAlise.OneDrive.Models.OutlierContainerType? OutlierContainerType { get; set; }
        /// <summary>The outlierMemberType property</summary>
        public global::MissAlise.OneDrive.Models.OutlierMemberType? OutlierMemberType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MissAlise.OneDrive.Models.MembershipOutlierInsight"/> and sets the default values.
        /// </summary>
        public MembershipOutlierInsight() : base()
        {
            OdataType = "#microsoft.graph.membershipOutlierInsight";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.MembershipOutlierInsight"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.MembershipOutlierInsight CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.MembershipOutlierInsight();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "container", n => { Container = n.GetObjectValue<global::MissAlise.OneDrive.Models.DirectoryObject>(global::MissAlise.OneDrive.Models.DirectoryObject.CreateFromDiscriminatorValue); } },
                { "containerId", n => { ContainerId = n.GetStringValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetObjectValue<global::MissAlise.OneDrive.Models.User>(global::MissAlise.OneDrive.Models.User.CreateFromDiscriminatorValue); } },
                { "member", n => { Member = n.GetObjectValue<global::MissAlise.OneDrive.Models.DirectoryObject>(global::MissAlise.OneDrive.Models.DirectoryObject.CreateFromDiscriminatorValue); } },
                { "memberId", n => { MemberId = n.GetStringValue(); } },
                { "outlierContainerType", n => { OutlierContainerType = n.GetEnumValue<global::MissAlise.OneDrive.Models.OutlierContainerType>(); } },
                { "outlierMemberType", n => { OutlierMemberType = n.GetEnumValue<global::MissAlise.OneDrive.Models.OutlierMemberType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DirectoryObject>("container", Container);
            writer.WriteStringValue("containerId", ContainerId);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.User>("lastModifiedBy", LastModifiedBy);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.DirectoryObject>("member", Member);
            writer.WriteStringValue("memberId", MemberId);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.OutlierContainerType>("outlierContainerType", OutlierContainerType);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.OutlierMemberType>("outlierMemberType", OutlierMemberType);
        }
    }
}
#pragma warning restore CS0618
