// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    /// <summary>
    /// Abstract class to contain properties used to assign a mobile app to a group.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MobileAppAssignmentSettings : IParsable
    {
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.MobileAppAssignmentSettings"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.MobileAppAssignmentSettings CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.iosLobAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.IosLobAppAssignmentSettings(),
                "#microsoft.graph.iosStoreAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.IosStoreAppAssignmentSettings(),
                "#microsoft.graph.iosVppAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.IosVppAppAssignmentSettings(),
                "#microsoft.graph.macOsLobAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.MacOsLobAppAssignmentSettings(),
                "#microsoft.graph.microsoftStoreForBusinessAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.MicrosoftStoreForBusinessAppAssignmentSettings(),
                "#microsoft.graph.win32LobAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.Win32LobAppAssignmentSettings(),
                "#microsoft.graph.windowsAppXAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.WindowsAppXAppAssignmentSettings(),
                "#microsoft.graph.windowsUniversalAppXAppAssignmentSettings" => new global::MissAlise.OneDrive.Models.WindowsUniversalAppXAppAssignmentSettings(),
                _ => new global::MissAlise.OneDrive.Models.MobileAppAssignmentSettings(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("@odata.type", OdataType);
        }
    }
}
#pragma warning restore CS0618
