// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServiceStatus : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The type of consumer. The possible values are: unknown, firstparty, thirdparty, unknownFutureValue.</summary>
        public global::MissAlise.OneDrive.Models.BackupServiceConsumer? BackupServiceConsumer { get; set; }
        /// <summary>The reason the service is disabled. The possible values are: none, controllerServiceAppDeleted, invalidBillingProfile, userRequested, unknownFutureValue.</summary>
        public global::MissAlise.OneDrive.Models.DisableReason? DisableReason { get; set; }
        /// <summary>The expiration time of the grace period.</summary>
        public DateTimeOffset? GracePeriodDateTime { get; set; }
        /// <summary>Identity of the person who last modified the entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.IdentitySet? LastModifiedBy { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.IdentitySet LastModifiedBy { get; set; }
#endif
        /// <summary>Timestamp of the last modification of the entity.</summary>
        public DateTimeOffset? LastModifiedDateTime { get; set; }
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>The expiration time of the restoration allowed period.</summary>
        public DateTimeOffset? RestoreAllowedTillDateTime { get; set; }
        /// <summary>Status of the service. This value indicates what capabilities can be used. The possible values are: disabled, enabled, protectionChangeLocked, restoreLocked, unknownFutureValue.</summary>
        public global::MissAlise.OneDrive.Models.BackupServiceStatus? Status { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.ServiceStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.ServiceStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.ServiceStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backupServiceConsumer", n => { BackupServiceConsumer = n.GetEnumValue<global::MissAlise.OneDrive.Models.BackupServiceConsumer>(); } },
                { "disableReason", n => { DisableReason = n.GetEnumValue<global::MissAlise.OneDrive.Models.DisableReason>(); } },
                { "gracePeriodDateTime", n => { GracePeriodDateTime = n.GetDateTimeOffsetValue(); } },
                { "lastModifiedBy", n => { LastModifiedBy = n.GetObjectValue<global::MissAlise.OneDrive.Models.IdentitySet>(global::MissAlise.OneDrive.Models.IdentitySet.CreateFromDiscriminatorValue); } },
                { "lastModifiedDateTime", n => { LastModifiedDateTime = n.GetDateTimeOffsetValue(); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "restoreAllowedTillDateTime", n => { RestoreAllowedTillDateTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::MissAlise.OneDrive.Models.BackupServiceStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.BackupServiceConsumer>("backupServiceConsumer", BackupServiceConsumer);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.DisableReason>("disableReason", DisableReason);
            writer.WriteDateTimeOffsetValue("gracePeriodDateTime", GracePeriodDateTime);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.IdentitySet>("lastModifiedBy", LastModifiedBy);
            writer.WriteDateTimeOffsetValue("lastModifiedDateTime", LastModifiedDateTime);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteDateTimeOffsetValue("restoreAllowedTillDateTime", RestoreAllowedTillDateTime);
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.BackupServiceStatus>("status", Status);
        }
    }
}
#pragma warning restore CS0618
