// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ShiftAvailability : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Specifies the pattern for recurrence</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.PatternedRecurrence? Recurrence { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.PatternedRecurrence Recurrence { get; set; }
#endif
        /// <summary>The time slot(s) preferred by the user.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.TimeRange>? TimeSlots { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.TimeRange> TimeSlots { get; set; }
#endif
        /// <summary>Specifies the time zone for the indicated time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeZone { get; set; }
#nullable restore
#else
        public string TimeZone { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.ShiftAvailability"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.ShiftAvailability CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.ShiftAvailability();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "recurrence", n => { Recurrence = n.GetObjectValue<global::MissAlise.OneDrive.Models.PatternedRecurrence>(global::MissAlise.OneDrive.Models.PatternedRecurrence.CreateFromDiscriminatorValue); } },
                { "timeSlots", n => { TimeSlots = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.TimeRange>(global::MissAlise.OneDrive.Models.TimeRange.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timeZone", n => { TimeZone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.PatternedRecurrence>("recurrence", Recurrence);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.TimeRange>("timeSlots", TimeSlots);
            writer.WriteStringValue("timeZone", TimeZone);
        }
    }
}
#pragma warning restore CS0618
