// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SimulationReport : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Overview of an attack simulation and training campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.SimulationReportOverview? Overview { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.SimulationReportOverview Overview { get; set; }
#endif
        /// <summary>The tenant users and their online actions in an attack simulation and training campaign.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.UserSimulationDetails>? SimulationUsers { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.UserSimulationDetails> SimulationUsers { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.SimulationReport"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.SimulationReport CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.SimulationReport();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "overview", n => { Overview = n.GetObjectValue<global::MissAlise.OneDrive.Models.SimulationReportOverview>(global::MissAlise.OneDrive.Models.SimulationReportOverview.CreateFromDiscriminatorValue); } },
                { "simulationUsers", n => { SimulationUsers = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.UserSimulationDetails>(global::MissAlise.OneDrive.Models.UserSimulationDetails.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.SimulationReportOverview>("overview", Overview);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.UserSimulationDetails>("simulationUsers", SimulationUsers);
        }
    }
}
#pragma warning restore CS0618
