// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SynchronizationStatus : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code property</summary>
        public global::MissAlise.OneDrive.Models.SynchronizationStatusCode? Code { get; set; }
        /// <summary>Number of consecutive times this job failed.</summary>
        public long? CountSuccessiveCompleteFailures { get; set; }
        /// <summary>true if the job&apos;s escrows (object-level errors) were pruned during initial synchronization. Escrows can be pruned if during the initial synchronization, you reach the threshold of errors that would normally put the job in quarantine. Instead of going into quarantine, the synchronization process clears the job&apos;s errors and continues until the initial synchronization is completed. When the initial synchronization is completed, the job will pause and wait for the customer to clean up the errors.</summary>
        public bool? EscrowsPruned { get; set; }
        /// <summary>Details of the last execution of the job.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution? LastExecution { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution LastExecution { get; set; }
#endif
        /// <summary>Details of the last execution of this job, which didn&apos;t have any errors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution? LastSuccessfulExecution { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution LastSuccessfulExecution { get; set; }
#endif
        /// <summary>Details of the last execution of the job, which exported objects into the target directory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution? LastSuccessfulExecutionWithExports { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.SynchronizationTaskExecution LastSuccessfulExecutionWithExports { get; set; }
#endif
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType { get; set; }
#nullable restore
#else
        public string OdataType { get; set; }
#endif
        /// <summary>Details of the progress of a job toward completion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SynchronizationProgress>? Progress { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SynchronizationProgress> Progress { get; set; }
#endif
        /// <summary>If job is in quarantine, quarantine details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.SynchronizationQuarantine? Quarantine { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.SynchronizationQuarantine Quarantine { get; set; }
#endif
        /// <summary>The time when steady state (no more changes to the process) was first achieved. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.</summary>
        public DateTimeOffset? SteadyStateFirstAchievedTime { get; set; }
        /// <summary>The time when steady state (no more changes to the process) was last achieved. The Timestamp type represents date and time information using ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.</summary>
        public DateTimeOffset? SteadyStateLastAchievedTime { get; set; }
        /// <summary>Count of synchronized objects, listed by object type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.StringKeyLongValuePair>? SynchronizedEntryCountByType { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.StringKeyLongValuePair> SynchronizedEntryCountByType { get; set; }
#endif
        /// <summary>In the event of an error, the URL with the troubleshooting steps for the issue.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TroubleshootingUrl { get; set; }
#nullable restore
#else
        public string TroubleshootingUrl { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.SynchronizationStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MissAlise.OneDrive.Models.SynchronizationStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.SynchronizationStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetEnumValue<global::MissAlise.OneDrive.Models.SynchronizationStatusCode>(); } },
                { "countSuccessiveCompleteFailures", n => { CountSuccessiveCompleteFailures = n.GetLongValue(); } },
                { "escrowsPruned", n => { EscrowsPruned = n.GetBoolValue(); } },
                { "lastExecution", n => { LastExecution = n.GetObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>(global::MissAlise.OneDrive.Models.SynchronizationTaskExecution.CreateFromDiscriminatorValue); } },
                { "lastSuccessfulExecution", n => { LastSuccessfulExecution = n.GetObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>(global::MissAlise.OneDrive.Models.SynchronizationTaskExecution.CreateFromDiscriminatorValue); } },
                { "lastSuccessfulExecutionWithExports", n => { LastSuccessfulExecutionWithExports = n.GetObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>(global::MissAlise.OneDrive.Models.SynchronizationTaskExecution.CreateFromDiscriminatorValue); } },
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "progress", n => { Progress = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationProgress>(global::MissAlise.OneDrive.Models.SynchronizationProgress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quarantine", n => { Quarantine = n.GetObjectValue<global::MissAlise.OneDrive.Models.SynchronizationQuarantine>(global::MissAlise.OneDrive.Models.SynchronizationQuarantine.CreateFromDiscriminatorValue); } },
                { "steadyStateFirstAchievedTime", n => { SteadyStateFirstAchievedTime = n.GetDateTimeOffsetValue(); } },
                { "steadyStateLastAchievedTime", n => { SteadyStateLastAchievedTime = n.GetDateTimeOffsetValue(); } },
                { "synchronizedEntryCountByType", n => { SynchronizedEntryCountByType = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.StringKeyLongValuePair>(global::MissAlise.OneDrive.Models.StringKeyLongValuePair.CreateFromDiscriminatorValue)?.AsList(); } },
                { "troubleshootingUrl", n => { TroubleshootingUrl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::MissAlise.OneDrive.Models.SynchronizationStatusCode>("code", Code);
            writer.WriteLongValue("countSuccessiveCompleteFailures", CountSuccessiveCompleteFailures);
            writer.WriteBoolValue("escrowsPruned", EscrowsPruned);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>("lastExecution", LastExecution);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>("lastSuccessfulExecution", LastSuccessfulExecution);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.SynchronizationTaskExecution>("lastSuccessfulExecutionWithExports", LastSuccessfulExecutionWithExports);
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationProgress>("progress", Progress);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.SynchronizationQuarantine>("quarantine", Quarantine);
            writer.WriteDateTimeOffsetValue("steadyStateFirstAchievedTime", SteadyStateFirstAchievedTime);
            writer.WriteDateTimeOffsetValue("steadyStateLastAchievedTime", SteadyStateLastAchievedTime);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.StringKeyLongValuePair>("synchronizedEntryCountByType", SynchronizedEntryCountByType);
            writer.WriteStringValue("troubleshootingUrl", TroubleshootingUrl);
        }
    }
}
#pragma warning restore CS0618
