// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Synchronization : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Performs synchronization by periodically running in the background, polling for changes in one directory, and pushing them to another directory.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SynchronizationJob>? Jobs { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SynchronizationJob> Jobs { get; set; }
#endif
        /// <summary>Represents a collection of credentials to access provisioned cloud applications.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SynchronizationSecretKeyStringValuePair>? Secrets { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SynchronizationSecretKeyStringValuePair> Secrets { get; set; }
#endif
        /// <summary>Preconfigured synchronization settings for a particular application.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SynchronizationTemplate>? Templates { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SynchronizationTemplate> Templates { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.Synchronization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.Synchronization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.Synchronization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "jobs", n => { Jobs = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationJob>(global::MissAlise.OneDrive.Models.SynchronizationJob.CreateFromDiscriminatorValue)?.AsList(); } },
                { "secrets", n => { Secrets = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationSecretKeyStringValuePair>(global::MissAlise.OneDrive.Models.SynchronizationSecretKeyStringValuePair.CreateFromDiscriminatorValue)?.AsList(); } },
                { "templates", n => { Templates = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationTemplate>(global::MissAlise.OneDrive.Models.SynchronizationTemplate.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationJob>("jobs", Jobs);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationSecretKeyStringValuePair>("secrets", Secrets);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SynchronizationTemplate>("templates", Templates);
        }
    }
}
#pragma warning restore CS0618
