// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models
{
    /// <summary>
    /// The user experience analytics metric for work from anywhere report.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserExperienceAnalyticsWorkFromAnywhereMetric : global::MissAlise.OneDrive.Models.Entity, IParsable
    {
        /// <summary>The work from anywhere metric devices. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereDevice>? MetricDevices { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereDevice> MetricDevices { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereMetric"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereMetric CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereMetric();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "metricDevices", n => { MetricDevices = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereDevice>(global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereDevice.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.UserExperienceAnalyticsWorkFromAnywhereDevice>("metricDevices", MetricDevices);
        }
    }
}
#pragma warning restore CS0618
