@MissAlise.WebApi_HostAddress = http://alise.com:5001

GET {{MissAlise.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MissAlise.WebApi_HostAddress}}/login/files

###

GET {{MissAlise.WebApi_HostAddress}}/

###
