@MissAlise.WebApi_HostAddress = https://localhost:5422

GET {{MissAlise.WebApi_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MissAlise.WebApi_HostAddress}}/login/files

###

GET {{MissAlise.WebApi_HostAddress}}/

###

GET {{MissAlise.WebApi_HostAddress}}/login/auth

###

GET {{MissAlise.WebApi_HostAddress}}/login/auth

###
