<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
  </PropertyGroup>

  <ItemGroup>    
    <ProjectReference Include="..\MissAlise.ServiceDefaults\MissAlise.Shared.csproj" />
    <ProjectReference Include="..\MissAlise\MissAlise.csproj" />
  </ItemGroup>

  <ItemGroup>  
    <PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.16.4" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\" />
  </ItemGroup>

</Project>
