<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
		<RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\MissAlise.ServiceDefaults\MissAlise.Shared.csproj" />
		<ProjectReference Include="..\MissAlise\MissAlise.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="14.0.0" />
		<PackageReference Include="AutoMapper.AspNetCore.OData.EFCore" Version="7.0.0" />
		<PackageReference Include="AutoMapper.Extensions.ExpressionMapping" Version="8.0.0" />
		<PackageReference Include="MediatR" Version="12.4.1" />
		<PackageReference Include="Telegram.Bot" Version="22.4.4" />
		<!--<PackageReference Include="Microsoft.Graph" Version="5.70.0" />-->
		<PackageReference Include="Microsoft.Kiota.Abstractions" Version="1.17.1" />
	</ItemGroup>
	<!--<ItemGroup>
		<Compile Include="..\MissAlise.OneDrive\Models\**\*">
			<Link>MissAlise.OneDrive\%(RecursiveDir)/%(FileName)%(Extension)</Link>			
		</Compile>
	</ItemGroup>-->
</Project>
