// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MissAlise.OneDrive.Models.Security
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Security : global::MissAlise.OneDrive.Models.Entity, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The alerts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.Alert>? Alerts { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.Alert> Alerts { get; set; }
#endif
        /// <summary>A collection of alerts in Microsoft 365 Defender.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.Security.Alert>? AlertsV2 { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.Security.Alert> AlertsV2 { get; set; }
#endif
        /// <summary>The attackSimulation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.AttackSimulationRoot? AttackSimulation { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.AttackSimulationRoot AttackSimulation { get; set; }
#endif
        /// <summary>The cases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.CasesRoot? Cases { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.CasesRoot Cases { get; set; }
#endif
        /// <summary>A container for security identities APIs.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.IdentityContainer? Identities { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.IdentityContainer Identities { get; set; }
#endif
        /// <summary>A collection of incidents in Microsoft 365 Defender, each of which is a set of correlated alerts and associated metadata that reflects the story of an attack.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.Security.Incident>? Incidents { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.Security.Incident> Incidents { get; set; }
#endif
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.LabelsRoot? Labels { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.LabelsRoot Labels { get; set; }
#endif
        /// <summary>The secureScoreControlProfiles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SecureScoreControlProfile>? SecureScoreControlProfiles { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SecureScoreControlProfile> SecureScoreControlProfiles { get; set; }
#endif
        /// <summary>The secureScores property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SecureScore>? SecureScores { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SecureScore> SecureScores { get; set; }
#endif
        /// <summary>The subjectRightsRequests property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MissAlise.OneDrive.Models.SubjectRightsRequest>? SubjectRightsRequests { get; set; }
#nullable restore
#else
        public List<global::MissAlise.OneDrive.Models.SubjectRightsRequest> SubjectRightsRequests { get; set; }
#endif
        /// <summary>The threatIntelligence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.ThreatIntelligence? ThreatIntelligence { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.ThreatIntelligence ThreatIntelligence { get; set; }
#endif
        /// <summary>The triggers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.TriggersRoot? Triggers { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.TriggersRoot Triggers { get; set; }
#endif
        /// <summary>The triggerTypes property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MissAlise.OneDrive.Models.Security.TriggerTypesRoot? TriggerTypes { get; set; }
#nullable restore
#else
        public global::MissAlise.OneDrive.Models.Security.TriggerTypesRoot TriggerTypes { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MissAlise.OneDrive.Models.Security.Security"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::MissAlise.OneDrive.Models.Security.Security CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::MissAlise.OneDrive.Models.Security.Security();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "alerts", n => { Alerts = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Alert>(global::MissAlise.OneDrive.Models.Alert.CreateFromDiscriminatorValue)?.AsList(); } },
                { "alerts_v2", n => { AlertsV2 = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Security.Alert>(global::MissAlise.OneDrive.Models.Security.Alert.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attackSimulation", n => { AttackSimulation = n.GetObjectValue<global::MissAlise.OneDrive.Models.AttackSimulationRoot>(global::MissAlise.OneDrive.Models.AttackSimulationRoot.CreateFromDiscriminatorValue); } },
                { "cases", n => { Cases = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.CasesRoot>(global::MissAlise.OneDrive.Models.Security.CasesRoot.CreateFromDiscriminatorValue); } },
                { "identities", n => { Identities = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.IdentityContainer>(global::MissAlise.OneDrive.Models.Security.IdentityContainer.CreateFromDiscriminatorValue); } },
                { "incidents", n => { Incidents = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Security.Incident>(global::MissAlise.OneDrive.Models.Security.Incident.CreateFromDiscriminatorValue)?.AsList(); } },
                { "labels", n => { Labels = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.LabelsRoot>(global::MissAlise.OneDrive.Models.Security.LabelsRoot.CreateFromDiscriminatorValue); } },
                { "secureScoreControlProfiles", n => { SecureScoreControlProfiles = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SecureScoreControlProfile>(global::MissAlise.OneDrive.Models.SecureScoreControlProfile.CreateFromDiscriminatorValue)?.AsList(); } },
                { "secureScores", n => { SecureScores = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SecureScore>(global::MissAlise.OneDrive.Models.SecureScore.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subjectRightsRequests", n => { SubjectRightsRequests = n.GetCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SubjectRightsRequest>(global::MissAlise.OneDrive.Models.SubjectRightsRequest.CreateFromDiscriminatorValue)?.AsList(); } },
                { "threatIntelligence", n => { ThreatIntelligence = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.ThreatIntelligence>(global::MissAlise.OneDrive.Models.Security.ThreatIntelligence.CreateFromDiscriminatorValue); } },
                { "triggerTypes", n => { TriggerTypes = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.TriggerTypesRoot>(global::MissAlise.OneDrive.Models.Security.TriggerTypesRoot.CreateFromDiscriminatorValue); } },
                { "triggers", n => { Triggers = n.GetObjectValue<global::MissAlise.OneDrive.Models.Security.TriggersRoot>(global::MissAlise.OneDrive.Models.Security.TriggersRoot.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Alert>("alerts", Alerts);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Security.Alert>("alerts_v2", AlertsV2);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.AttackSimulationRoot>("attackSimulation", AttackSimulation);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.CasesRoot>("cases", Cases);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.IdentityContainer>("identities", Identities);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.Security.Incident>("incidents", Incidents);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.LabelsRoot>("labels", Labels);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SecureScoreControlProfile>("secureScoreControlProfiles", SecureScoreControlProfiles);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SecureScore>("secureScores", SecureScores);
            writer.WriteCollectionOfObjectValues<global::MissAlise.OneDrive.Models.SubjectRightsRequest>("subjectRightsRequests", SubjectRightsRequests);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.ThreatIntelligence>("threatIntelligence", ThreatIntelligence);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.TriggersRoot>("triggers", Triggers);
            writer.WriteObjectValue<global::MissAlise.OneDrive.Models.Security.TriggerTypesRoot>("triggerTypes", TriggerTypes);
        }
    }
}
#pragma warning restore CS0618
