<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>annotations</Nullable>
    <RootNamespace>$(MSBuildProjectName.Replace("_", "").Replace(".Common", ""))</RootNamespace>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MissAlise.Application\MissAlise.Application.csproj" />
	</ItemGroup>
</Project>
