<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="linq2db.EntityFrameworkCore" Version="8.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
		<PackageReference Include="EfCore.SchemaCompare" Version="8.2.0" />
		<PackageReference Include="MongoDB.Driver" Version="3.2.1" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />		
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.11" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" Condition="'$(Configuration)' == 'Debug'">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.11">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>		
		<PackageReference Include="System.Text.Json" Version="9.0.2" />  
	</ItemGroup>	
	<ItemGroup>
		<ProjectReference Include="..\MissAlise.Application\MissAlise.Application.csproj" />
		<ProjectReference Include="..\MissAlise.Background.Abstractions\MissAlise.Background.Abstractions.csproj" />
	</ItemGroup>

</Project>
