<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="linq2db.EntityFrameworkCore" Version="8.1.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.11" />
		<PackageReference Include="MongoDB.Driver" Version="3.1.0" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
		<PackageReference Include="System.Text.Json" Version="9.0.1" />  
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.11" Condition="'$(Configuration)' == 'Debug'">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>	
	<ItemGroup>
		<ProjectReference Include="..\MissAlise.Application\MissAlise.Application.csproj" />
		<ProjectReference Include="..\MissAlise.Background.Abstractions\MissAlise.Background.Abstractions.csproj" />
	</ItemGroup>

</Project>
