// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MissAlise.DataBase.Models;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MissAlise.DataBase.Migrations
{
    [DbContext(typeof(UserMediaContext))]
    [Migration("20250109130306_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MissAlise.DataBase.Models.Item", b =>
                {
                    b.Property<int>("Itemid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Itemid"));

                    b.Property<DateTime?>("Createddatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Itemid");

                    b.ToTable("Items");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int?>("StorageFolderItemid")
                        .HasColumnType("integer");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserPrincipalName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("StorageFolderItemid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.File", b =>
                {
                    b.HasBaseType("MissAlise.DataBase.Models.Item");

                    b.Property<string>("Extension")
                        .HasColumnType("text");

                    b.Property<int>("Fileid")
                        .HasColumnType("integer");

                    b.Property<int?>("FolderItemid")
                        .HasColumnType("integer");

                    b.Property<string>("Mimetype")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Size")
                        .HasColumnType("integer");

                    b.HasIndex("FolderItemid");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Folder", b =>
                {
                    b.HasBaseType("MissAlise.DataBase.Models.Item");

                    b.Property<int>("Folderid")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("Parentfolderid")
                        .HasColumnType("integer");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasIndex("Parentfolderid");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Audio", b =>
                {
                    b.HasBaseType("MissAlise.DataBase.Models.File");

                    b.Property<string>("Album")
                        .HasColumnType("text");

                    b.Property<string>("Artist")
                        .HasColumnType("text");

                    b.Property<int>("Audioid")
                        .HasColumnType("integer");

                    b.Property<long?>("Bitrate")
                        .HasColumnType("bigint");

                    b.Property<int?>("Disc")
                        .HasColumnType("integer");

                    b.Property<long?>("Duration")
                        .HasColumnType("bigint");

                    b.Property<string>("Genre")
                        .HasColumnType("text");

                    b.Property<int?>("Track")
                        .HasColumnType("integer");

                    b.Property<string>("TrackTitle")
                        .HasColumnType("text");

                    b.Property<int?>("Trackcount")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.ToTable("Audios");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Photo", b =>
                {
                    b.HasBaseType("MissAlise.DataBase.Models.File");

                    b.Property<string>("Cameramake")
                        .HasColumnType("text");

                    b.Property<string>("Cameramodel")
                        .HasColumnType("text");

                    b.Property<double?>("Exposuredenominator")
                        .HasColumnType("double precision");

                    b.Property<double?>("Exposurenumerator")
                        .HasColumnType("double precision");

                    b.Property<double?>("Fnumber")
                        .HasColumnType("double precision");

                    b.Property<double?>("Focallength")
                        .HasColumnType("double precision");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int?>("Iso")
                        .HasColumnType("integer");

                    b.Property<int?>("Orientation")
                        .HasColumnType("integer");

                    b.Property<int>("Photoid")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Takendatetime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Video", b =>
                {
                    b.HasBaseType("MissAlise.DataBase.Models.File");

                    b.Property<int?>("Audiobitspersample")
                        .HasColumnType("integer");

                    b.Property<int?>("Audiochannels")
                        .HasColumnType("integer");

                    b.Property<string>("Audioformat")
                        .HasColumnType("text");

                    b.Property<int?>("Audiosamplespersecond")
                        .HasColumnType("integer");

                    b.Property<int?>("Bitrate")
                        .HasColumnType("integer");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("interval");

                    b.Property<string>("Fourcc")
                        .HasColumnType("text");

                    b.Property<double?>("Framerate")
                        .HasColumnType("double precision");

                    b.Property<int?>("Height")
                        .HasColumnType("integer");

                    b.Property<int>("Videoid")
                        .HasColumnType("integer");

                    b.Property<int?>("Width")
                        .HasColumnType("integer");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.User", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.Folder", "StorageFolder")
                        .WithMany()
                        .HasForeignKey("StorageFolderItemid");

                    b.Navigation("StorageFolder");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.File", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderItemid");

                    b.HasOne("MissAlise.DataBase.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("MissAlise.DataBase.Models.File", "Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Folder", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.Item", null)
                        .WithOne()
                        .HasForeignKey("MissAlise.DataBase.Models.Folder", "Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MissAlise.DataBase.Models.Folder", "Parent")
                        .WithMany("Folders")
                        .HasForeignKey("Parentfolderid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Audio", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.File", null)
                        .WithOne()
                        .HasForeignKey("MissAlise.DataBase.Models.Audio", "Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Photo", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.File", null)
                        .WithOne()
                        .HasForeignKey("MissAlise.DataBase.Models.Photo", "Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Video", b =>
                {
                    b.HasOne("MissAlise.DataBase.Models.File", null)
                        .WithOne()
                        .HasForeignKey("MissAlise.DataBase.Models.Video", "Itemid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MissAlise.DataBase.Models.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Folders");
                });
#pragma warning restore 612, 618
        }
    }
}
