<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>annotations</Nullable>
		<RunAnalyzersDuringLiveAnalysis>False</RunAnalyzersDuringLiveAnalysis>
		<RunAnalyzersDuringBuild>False</RunAnalyzersDuringBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Azure.Core" Version="1.45.0" />
		<PackageReference Include="Azure.Identity" Version="1.13.2" />
		<PackageReference Include="Microsoft.Graph.Core" Version="3.2.3" />
		<PackageReference Include="Microsoft.Kiota.Authentication.Azure" Version="1.17.1" />
		<PackageReference Include="Microsoft.Kiota.Bundle" Version="1.17.1" />
		<PackageReference Include="Microsoft.Kiota.Serialization.Json" Version="1.17.1" />
		<PackageReference Include="Refit" Version="8.0.0" />
		<PackageReference Include="Refit.HttpClientFactory" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\MissAlise.Application\MissAlise.Application.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Compile Remove="Models\**\*" />		
	</ItemGroup>
</Project>
